### PR TITLE
Hide user interface and skip desktop directory for sevice applications

### LINKED ISSUE #56: System.ArgumentException at nUpdate.UpdateInstaller.Updater.CopyDirectoryRecursively()
If i try to make an update with an application that run as service i get the following exception : 

```
System.ArgumentException: Der Pfad darf keine leere Zeichenfolge sein oder nur aus Leerzeichen bestehen.
   bei System.IO.Directory.CreateDirectory(String path)
   bei nUpdate.UpdateInstaller.Updater.CopyDirectoryRecursively(String sourceDirName, String destDirName) 
```

while debugging or if running as normal ui application, the exception doesnt occurs

any ideas ?

### PR DESCRIPTION
**Pull request by swASO**
fix #56

### CODE REVIEW

File: nUpdate.UpdateInstaller/WindowsServiceHelper.cs [hunk 1]
```diff
@@ -0,0 +1,37 @@
...
+        private static bool? _IsRunningInServiceContext;
+
+        /// <summary>
+        /// Indicates if the application runs in service context
+        /// </summary>
+        public static bool IsRunningInServiceContext => _IsRunningInServiceContext ?? (_IsRunningInServiceContext = DetermineIfRunningInServiceContext()).Value; 
+
+
+
+        private static bool DetermineIfRunningInServiceContext()
```
Comment (swASO) [inline nUpdate.UpdateInstaller/WindowsServiceHelper.cs]: i would say we have one condition that we cant catch 
the application runs as service, has "allow service to interact with desktop" checked and! he has change the user ( login with ... )

File: nUpdate.UpdateInstaller/Core/ProgressReporterService.cs [hunk 2]
```diff
@@ -26,6 +27,14 @@ public void Fail(Exception ex)
         public void Initialize()
         {
             _mainForm?.Initialize();
+
+            if(WindowsServiceHelper.IsRunningInServiceContext)
+            {
+                while (shouldRun)
```
Comment (ProgTrade) [inline nUpdate.UpdateInstaller/Core/ProgressReporterService.cs]: What is that for?

File: nUpdate.UpdateInstaller/Program.cs [hunk 3]
```diff
@@ -3,6 +3,7 @@
 using System;
 using System.Collections.Generic;
 using System.Drawing;
+using System.IO;
```
Comment (ProgTrade) [inline nUpdate.UpdateInstaller/Program.cs]: What is the namespace for?

File: nUpdate.UpdateInstaller/WindowsServiceHelper.cs [hunk 4]
```diff
@@ -0,0 +1,37 @@
...
+using System.Collections.Generic;
+using System.IO;
+using System.Linq;
+using System.Text;
+
+namespace nUpdate.UpdateInstaller
+{
+    public static class WindowsServiceHelper
+    {
+        private static bool? _IsRunningInServiceContext;
```
Comment (ProgTrade) [inline nUpdate.UpdateInstaller/WindowsServiceHelper.cs]: Please use lower camel case: "_isRunningInServiceContext"

File: nUpdate.WPFUpdateInstaller/Program.cs [hunk 5]
```diff
@@ -1,5 +1,6 @@
 ﻿using System;
 using System.Collections.Generic;
+using System.IO;
```
Comment (ProgTrade) [inline nUpdate.WPFUpdateInstaller/Program.cs]: What is the namespace for?

File: nUpdate.UpdateInstaller/WindowsServiceHelper.cs [hunk 6]
```diff
@@ -0,0 +1,37 @@
...
+
+        /// <summary>
+        /// Indicates if the application runs in service context
```
Comment (ProgTrade) [inline nUpdate.UpdateInstaller/WindowsServiceHelper.cs]: Please start the doc with "Gets a value indicating, if ..."

File: nUpdate.UpdateInstaller/Core/ProgressReporterServiceEventLog.cs [hunk 7]
```diff
@@ -0,0 +1,45 @@
...
+            WindowsEventLog.LogException(ex);
+        }
+
+        public void Initialize()
+        {
+            if(WindowsServiceHelper.IsRunningInServiceContext)
+            {
+                while (shouldRun)
+                {
+                    System.Threading.Thread.Sleep(2000);
```
Comment (ProgTrade) [inline nUpdate.UpdateInstaller/Core/ProgressReporterServiceEventLog.cs]: What is that for?

File: nUpdate.UpdateInstaller/UI/Popups/Popup.cs [hunk 8]
```diff
@@ -62,6 +72,10 @@ public static DialogResult ShowPopup(Icon popupIcon, string title, Exception ex,
         public static DialogResult ShowPopup(IWin32Window owner, Icon popupIcon, string title, string infoMessage,
             PopupButtons buttons)
         {
+            if (LoggedIntoEventlog(popupIcon, infoMessage))
```
Comment (ProgTrade) [inline nUpdate.UpdateInstaller/UI/Popups/Popup.cs]: What is the sense of that? This would suppress any popups and log the messages instead, wouldn't it? But, this is not what should happen when we want to see the messages inside a popup message. Or am I missing something?

File: nUpdate.UpdateInstaller/WindowsEventLog.cs [hunk 9]
```diff
@@ -0,0 +1,137 @@
...
+
+                CreateEventSourceIfnotExsists();
+            }
+        }
+        // https://stackoverflow.com/questions/25725151/write-to-windows-application-event-log
+        // Note: The actual limit is higher than this, but different Microsoft operating systems actually have different limits. So just use 30,000 to be safe.
+        private const int MaxEventLogEntryLength = 30000;
+
+
+        private static void CreateEventSourceIfnotExsists()
```
Comment (ProgTrade) [inline nUpdate.UpdateInstaller/WindowsEventLog.cs]: There is a typo. Actually, I would prefer simply the name `CreateEventSource`.

File: nUpdate.UpdateInstaller/WindowsEventLog.cs [hunk 10]
```diff
@@ -0,0 +1,137 @@
...
+using System.Reflection;
+using System.Security;
+using System.Text;
+
+namespace nUpdate.UpdateInstaller
+{
+    public static class WindowsEventLog
+    {
+        private const string DefaultSource = "nUpdate";
+        private static string _Source;
```
Comment (ProgTrade) [inline nUpdate.UpdateInstaller/WindowsEventLog.cs]: Please use lower camel case here as well.

File: nUpdate.UpdateInstaller/UI/Popups/Popup.cs (hunk 8 above)
Comment (swASO) [reply nUpdate.UpdateInstaller/UI/Popups/Popup.cs]: no, would not
if the application runs as service, you cant open dialogs- so we need to write in to the eventlog - without that we wouldn't see any messages/exceptions from nUpdate

you can open the window if "Environment.UserInteractive" is true, but in a terminel server environment every user would get a confusing popup. so i decide this would be the best solution

File: nUpdate.UpdateInstaller/Program.cs (hunk 3 above)
Comment (swASO) [reply nUpdate.UpdateInstaller/Program.cs]: forgot to cleanup

File: nUpdate.WPFUpdateInstaller/Program.cs (hunk 5 above)
Comment (swASO) [reply nUpdate.WPFUpdateInstaller/Program.cs]: forgot to cleanup

File: nUpdate.UpdateInstaller/WindowsServiceHelper.cs (hunk 6 above)
Comment (swASO) [reply nUpdate.UpdateInstaller/WindowsServiceHelper.cs]: done

File: nUpdate.UpdateInstaller/Core/ProgressReporterServiceEventLog.cs (hunk 7 above)
Comment (swASO) [reply nUpdate.UpdateInstaller/Core/ProgressReporterServiceEventLog.cs]: in desktop mode you open a window that prevent the application to close and do async update

in service mode, the window doesent exists, so we need to loop until the update is done

File: nUpdate.UpdateInstaller/WindowsEventLog.cs (hunk 9 above)
Comment (swASO) [reply nUpdate.UpdateInstaller/WindowsEventLog.cs]: done

File: nUpdate.UpdateInstaller/WindowsEventLog.cs (hunk 10 above)
Comment (swASO) [reply nUpdate.UpdateInstaller/WindowsEventLog.cs]: done

File: nUpdate.UpdateInstaller/Core/ProgressReporterServiceEventLog.cs (hunk 7 above)
Comment (ProgTrade) [reply nUpdate.UpdateInstaller/Core/ProgressReporterServiceEventLog.cs]: Ah, I see. Thought of something else here. Thanks.

File: nUpdate.UpdateInstaller/UI/Popups/Popup.cs (hunk 8 above)
Comment (ProgTrade) [reply nUpdate.UpdateInstaller/UI/Popups/Popup.cs]: The thing I think about is: Once we have an app runing as service, we do not initialize the usual reporter service with the integrated user interface (https://github.com/ProgTrade/nUpdate/pull/62/commits/956f956123bedcc3690318826a4695c916ad3b43#diff-b0b1bcab7f1b1a86e0c87a87fa9d91deR32). But, the MainForm is the only class that calls popups. So, isn't this call redundant then? When we do not show the MainForm at all in case of a service, we do not have other possibilites to create a popup in the update installer. Or am I missing a call? Or is this a general safety feature in case the popups may be used (accidentally)?

Comment (swASO) [reply nUpdate.UpdateInstaller/UI/Popups/Popup.cs]: [Program.cs#L158](https://github.com/ProgTrade/nUpdate/blob/master/nUpdate.UpdateInstaller/Program.cs#L158)
[Program.cs#L199](https://github.com/ProgTrade/nUpdate/blob/master/nUpdate.UpdateInstaller/Program.cs#L199)
[Updater.cs#L126](https://github.com/ProgTrade/nUpdate/blob/master/nUpdate.UpdateInstaller/Updater.cs#L126)

Comment (ProgTrade) [reply nUpdate.UpdateInstaller/UI/Popups/Popup.cs]: Okay, thanks. I don't know why I didn't remember/see these calls there. Seems to be a long time that I've written the code. =)

**Comment by ProgTrade** [comment]
Thank you!
