### PR TITLE
Fix #48 and add two properties to UpdateManager

### LINKED ISSUE #48: ProjectEdit throw an "InvalidOperationException"
Version: 3.2.1
ProjectEditDialog.cs
image
image
The exception message means "Cross-thread operation not valid: Control ‘ProjectEditDialog’ accessed from a thread other than the thread it was created on".

### PR DESCRIPTION
**Pull request by selway**
# Fixed #48 and add two properties for UpdateManager

- ## BUG

    - Fixed #48 and another same bug

        There is an improper use of accessing UI controls in non-UI threads in the "InitializeData" method of the "ProjectEditDialog" class.

        The original code: The "Popup.ShowPopup" method is called without "Invoke" in the "Task.Factory.StartNew method", and it is like this:

        ```C#
            private async void InitializeData()
            {
                await Task.Factory.StartNew(() =>
                {
                    ...
                    bool synchronizeData = Popup.ShowPopup(this, SystemIcons.Question, "Automatically synchronize data?",
                        "nUpdate Administration may encounter differences between your remote configuration and the local changes that you've made. Should nUpdate Administration try to synchronize these changes or do you want to keep them locally? Choose the latter option, if you just fixed a problem with the data (e.g. a typo due to which nUpdate Administration could not connect to the server).",
                        PopupButtons.YesNo) == DialogResult.Yes;
                    ...
                    if (Project.Path != _localPath)
                    {
                        if (Popup.ShowPopup(this, SystemIcons.Question, "Automatically move the project file?",
                            "nUpdate Administration noticed that the path of the local project file has changed. Should nUpdate Administration move it to this new location? Choose \"No\", if the file is already located at the path that you specified.",
                            PopupButtons.YesNo) == DialogResult.Yes)
                        {
                            ...
                        }
                        ...
                    }
                    ...
                }
            }
        ```

        P.S. Although the BUG does not always occur, but I still think it is better to fix it.

- ## Add

    - Add "SearchTimeout" property for "UpdateManager"

        This property gets or sets the timeout that should be used when searching for updates. By default, this is set to 10000 milliseconds.

    - Add "UseDynamicUpdateUri" property for "UpdateManager"

        - Description

            The proerty indicating whether the nUpdate set every update package URI (its parent directory) is automatically to the one that corresponds to the directory where also the configuration file is located before downloading update package. Default false.

            `UpdateConfigurationFileUri` is 'http://www.test.de/nNpdate/updates.json', version is '1.0.0.0', `UpdatePackageUri` is 'http://localhost/nNpdate/1.0.0.0/id.zip',  the nUpdate will download the update-packages from 'http://www.test.de/nNpdate/1.0.0.0/id.zip' instead of 'http://localhost/nNpdate/1.0.0.0/id.zip'.

        - Why add?

            When updating the same software in multiple networks that do not communicate, the user only need to create one nUpdate project to manage the upgrade package and then distribute the upgrade package to the servers in each network. Without this property, the user will need to create multiple nUpdate projects, or re-edit the nUpdate project or modify the `UpdatePackageUri` value of each `updates.json` before distribute the upgrade package to each server.

        - Use scene case of `UseDynamicUpdateUri`.

            One APP：APP-A. Multiple non communication LAN: LAN-1, LAN-2, ... LAN-N.

            LAN-1 Server IP：192.168.0.1.

            LAN-2 Server IP：192.168.2.1.

            ...

            LAN-N Server IP：192.168.N.1.

            When deploying APP-A's update-package for LAN-1, the user needs to create an nUpdate project and add an upgrade packages, and the. After completing the above operation, `updates.json` should be similar to the following.

            ``` json
            [
                {
                    "Architecture": 2,
                    "Changelog": {
                        "en": "..."
                    },
                    "LiteralVersion": "1.0.1.0",
                    "NecessaryUpdate": false,
                    "Operations": [],
                    "Signature": "sigin",
                    "UnsupportedVersions": null,
                    "UpdatePackageUri": "http://192.168.0.1/updater/1.0.1.0/6ab6501f-6557-4808-a68f-6c6fb34fb3e4.zip",
                    "UpdatePhpFileUri": "http://192.168.0.1/updater/statistics.php",
                    "UseStatistics": false,
                    "VersionId": 12
                }
            ]
            ```

            Now the user also needs to deploy APP-A's update-package for LAN-2. Since the server-IP of LAN-1 and LAN-2 are not the same, users cannot directly use `update.json` and upgrade packages in LAN-1. At this time, the user needs to re-edit the nUpdate project previously created or modify the `UpdatePackageUri` of `updates.json` or create a new nUpdate project for LAN-2. But I think these three methods are not convenient, so I added this property. This scene also applies to LAN-N.

            Another similar scenario is that the provider of the update package is not in the same network as the software user.

### CODE REVIEW

File: nUpdate.Administration/UI/Dialogs/ProjectEditDialog.cs [hunk 1]
```diff
@@ -994,9 +994,13 @@ private void continueButton_Click(object sender, EventArgs e)
                     _useStatistics = useStatisticsServerRadioButton.Checked;
```
[the remark this answers is not in the document]
Comment (selway) [reply nUpdate.Administration/UI/Dialogs/ProjectEditDialog.cs]: Sorry, I have not much experience. So I'm puzzled. I don't know how I need to change the "submit title". Can you give me a reference or convention description?

**Comment by selway** [comment]
About the `UseDynamicUpdateUri` property.

For example, there is now no communication LAN 1 and LAN 2, LAN 1 update server IP is 192.168.0.10, LAN 2 update server IP is 172.16.33.10. Users in the two LANs use the same application "Test" and update the same version. The application "Test" allows the user to modify the server IP of their communication.

Now we need to update the "test" version for users in LAN1. What do we need to do?
Create an nUpdate project named "test-update-lan1", set the update IP and FTP to "192.168.0.10", then open the project to add an update package, and upload it to the update server.

After completing the above update, how can we update the same version for users in LAN 2? Without this dynamic update URI feature, there is three ways:

- Same as last time, create an nUpdate project named "test-update-lan2", set the update IP and FTP to "172.16.33.10", open the project and add an update package, then upload it to the update server.
- Open the project "test-update-lan1", modify the update IP and FTP to "172.16.33.10", and select the synchronization data.
- Copy the update package from the LAN 1 server to the same directory on the LAN 2 server, and replace the IP in "updates.json" on the LAN 2 server with "172.16.33.10".

But with this feature, we only need to copy and copy the same directory from LAN 1 server to LAN 2 server.

Another similar scenario  is that software version maintainers cannot directly access the update server via FTP. At this time, we can only maintain the update package locally, and then upload it to the server through other methods, and then modify "update.json" or use this function without modifying any configuration.

File: nUpdate.Administration/UI/Dialogs/ProjectEditDialog.cs (hunk 1 above)
[the remark this answers is not in the document]
Comment (ProgTrade) [reply nUpdate.Administration/UI/Dialogs/ProjectEditDialog.cs]: The commit messages should be named so they fit in with the sentence "When applied, this commit will..."

So, it is only "Fixed #48 and another same bug" that does not correspond to the criteria. This would result in "When applied, this commit will fixed #48..." which is not correct. You understand, what I mean? So it should just be "Fix" instead of "Fixed". Then it is fine.

**Comment by ProgTrade** [comment]
Ah, I now understand the idea behind your dynamic update URI implementation. So, this is useful as soon as somebody just copies the update content to another server in case there are multiple non-communicating networks that wait for updates. Then the user just needs to do that without adjusting the package URLs everytime.

Okay, thanks. Then I will now check out the code for this implementation.

File: nUpdate.Shared/Updating/UpdateManager.cs [hunk 2]
```diff
@@ -472,5 +486,56 @@ bool Validate(KeyValuePair<UpdateVersion, string> filePathItem)
             Cleanup();
             return false;
         }
+
+        /// <summary>
+        ///     Convert <paramref name="updatePackageUri"/> (its parent directory <paramref name="literalVersion"/>) to the one that
```
Comment (ProgTrade) [inline nUpdate.Shared/Updating/UpdateManager.cs]: Just leave the documentation out here. It's redundant for private methods.

File: nUpdate.Shared/Updating/UpdateManager.cs [hunk 3]
```diff
@@ -472,5 +486,56 @@ bool Validate(KeyValuePair<UpdateVersion, string> filePathItem)
...
+        /// <exception cref="System.ArgumentNullException">updatePackageUri or literalVersion is null.</exception>
+        /// <exception cref="System.ArgumentException">literalVersion is a valid value. Reference <see cref="UpdateVersion"/></exception>
+        /// <exception cref="System.InvalidOperationException">updatePackageUri.AbsoluteUri is a valid uri.</exception>
+        private Uri ConvertPackageUri(Uri updatePackageUri, string literalVersion)
+        {
+            if (!UseDynamicUpdateUri)
+                return updatePackageUri;
+            if (updatePackageUri == null)
+                throw new ArgumentNullException(nameof(updatePackageUri));
+            if (literalVersion is null)
```
Comment (ProgTrade) [inline nUpdate.Shared/Updating/UpdateManager.cs]: You can leave this check out. `UpdateVersion.IsValid` implements `RegEx.IsMatch` which does automatically throw an ArgumentNullException in case `literalVersion` is null. Additionally, as this method is private, we can guarantee a correct usage.

File: nUpdate.Shared/Updating/UpdateManager.cs [hunk 4]
```diff
@@ -472,5 +486,56 @@ bool Validate(KeyValuePair<UpdateVersion, string> filePathItem)
...
+                throw new ArgumentNullException(nameof(literalVersion));
+            if (!UpdateVersion.IsValid(literalVersion))
+                throw new ArgumentException($"{literalVersion} is not valid value.", nameof(literalVersion));
```
Comment (ProgTrade) [inline nUpdate.Shared/Updating/UpdateManager.cs]: You replace the string argument by the name of the parameter. It would be better to use its value instead.

File: nUpdate.Shared/Updating/UpdateManager.cs [hunk 5]
```diff
@@ -472,5 +486,56 @@ bool Validate(KeyValuePair<UpdateVersion, string> filePathItem)
...
+            var packageName = updatePackageUri.AbsoluteUri.Substring(updatePackageUri.AbsoluteUri.LastIndexOf(@"/") + 1);
+            var updateConfigUrl = UpdateConfigurationFileUri.AbsoluteUri.Substring(0, UpdateConfigurationFileUri.AbsoluteUri.LastIndexOf(@"/"));
```
Comment (ProgTrade) [inline nUpdate.Shared/Updating/UpdateManager.cs]: Please rename this to "baseUri".
Make sure to check out the `Uri.GetLeftPart`-method which may replace the `Substring` function here:
`var baseUri = uri.GetLeftPart(System.UriPartial.Authority);`

File: nUpdate.Shared/Updating/UpdateManager.cs [hunk 6]
```diff
@@ -472,5 +486,56 @@ bool Validate(KeyValuePair<UpdateVersion, string> filePathItem)
...
+        {
+            if (!UseDynamicUpdateUri)
+                return updatePackageUri;
+            if (updatePackageUri == null)
+                throw new ArgumentNullException(nameof(updatePackageUri));
+            if (literalVersion is null)
+                throw new ArgumentNullException(nameof(literalVersion));
+            if (!UpdateVersion.IsValid(literalVersion))
+                throw new ArgumentException($"{literalVersion} is not valid value.", nameof(literalVersion));
+            var packageName = updatePackageUri.AbsoluteUri.Substring(updatePackageUri.AbsoluteUri.LastIndexOf(@"/") + 1);
```
Comment (ProgTrade) [inline nUpdate.Shared/Updating/UpdateManager.cs]: You could maybe use `Uri.Segments.Last()` here.

File: nUpdate.Shared/Updating/UpdateManager.cs [hunk 7]
```diff
@@ -472,5 +486,56 @@ bool Validate(KeyValuePair<UpdateVersion, string> filePathItem)
...
+        ///     If <see cref="UpdateManager.UseDynamicUpdateUri"/> is false, return the original value.</returns>
+        /// <exception cref="System.ArgumentNullException">statisticsUri is null.</exception>
+        /// <exception cref="System.InvalidOperationException">statisticsUri.AbsoluteUri is a valid uri.</exception>
+        private Uri ConvertStatisticsUri(Uri statisticsUri)
+        {
+            if (!UseDynamicUpdateUri)
+                return statisticsUri;
+            if (statisticsUri == null)
+                throw new ArgumentNullException(nameof(statisticsUri));
+            var packageName = statisticsUri.AbsoluteUri.Substring(statisticsUri.AbsoluteUri.LastIndexOf(@"/") + 1);
```
Comment (ProgTrade) [inline nUpdate.Shared/Updating/UpdateManager.cs]: The statistics file does not have a package name. It always is a "statistics.php". So, you can safely remove this and just finish the string with "statistics.php". Update dependant data will be handled over using URI parameters later.

File: nUpdate.Shared/Updating/UpdateManager.cs [hunk 8]
```diff
@@ -472,5 +486,56 @@ bool Validate(KeyValuePair<UpdateVersion, string> filePathItem)
...
+            var updateConfigUrl = UpdateConfigurationFileUri.AbsoluteUri.Substring(0, UpdateConfigurationFileUri.AbsoluteUri.LastIndexOf(@"/"));
```
Comment (ProgTrade) [inline nUpdate.Shared/Updating/UpdateManager.cs]: Please rename this to "baseUri".
Make sure to check out the `Uri.GetLeftPart`-method which may replace the `Substring` function here:
`var baseUri = uri.GetLeftPart(System.UriPartial.Authority);`

File: nUpdate.Test/UseDynamicUriTest.cs [hunk 9]
```diff
@@ -0,0 +1,100 @@
+﻿using System;
```
Comment (ProgTrade) [inline nUpdate.Test/UseDynamicUriTest.cs]: When you changed the implementation, it should be clear that you should run the unit tests again to see, if there are any changes necessary.

File: nUpdate.Shared/Updating/UpdateManager.cs [hunk 10]
```diff
@@ -472,5 +486,56 @@ bool Validate(KeyValuePair<UpdateVersion, string> filePathItem)
...
+        /// <param name="updatePackageUri">The update-packages uri. <see cref="UpdateConfiguration.UpdatePackageUri"/></param>
+        /// <param name="literalVersion">The update-packages literalVersion. <see cref="UpdateConfiguration.LiteralVersion"/></param>
+        /// <returns>
+        ///     Return converted URI.
+        ///     If <see cref="UpdateManager.UseDynamicUpdateUri"/> is false, return the original value.
+        /// </returns>
+        /// <exception cref="System.ArgumentNullException">updatePackageUri or literalVersion is null.</exception>
+        /// <exception cref="System.ArgumentException">literalVersion is a valid value. Reference <see cref="UpdateVersion"/></exception>
+        /// <exception cref="System.InvalidOperationException">updatePackageUri.AbsoluteUri is a valid uri.</exception>
+        private Uri ConvertPackageUri(Uri updatePackageUri, string literalVersion)
```
Comment (ProgTrade) [inline nUpdate.Shared/Updating/UpdateManager.cs]: Method names are sorted alphabetically. Please move them to the suitable position in the code within the other methods.

File: nUpdate.Shared/Updating/UpdateManager.cs [hunk 11]
```diff
@@ -472,5 +486,56 @@ bool Validate(KeyValuePair<UpdateVersion, string> filePathItem)
...
+                throw new ArgumentNullException(nameof(literalVersion));
+            if (!UpdateVersion.IsValid(literalVersion))
+                throw new ArgumentException($"{literalVersion} is not valid value.", nameof(literalVersion));
+            var packageName = updatePackageUri.AbsoluteUri.Substring(updatePackageUri.AbsoluteUri.LastIndexOf(@"/") + 1);
+            var updateConfigUrl = UpdateConfigurationFileUri.AbsoluteUri.Substring(0, UpdateConfigurationFileUri.AbsoluteUri.LastIndexOf(@"/"));
+            return new Uri($"{updateConfigUrl}/{literalVersion}/{packageName}");
+        }
+
+        /// <summary>
+        ///     Convert <paramref name="statisticsUri"/> to the one that corresponds to the directory
```
Comment (ProgTrade) [inline nUpdate.Shared/Updating/UpdateManager.cs]: Remove documentation as well.

File: nUpdate.Test/UseDynamicUriTest.cs [hunk 12]
```diff
@@ -0,0 +1,100 @@
...
+using Microsoft.VisualStudio.TestTools.UnitTesting;
+using nUpdate.Updating;
+
+namespace nUpdate.Test
+{
+    [TestClass]
+    public class UseDynamicUriTest
```
Comment (ProgTrade) [inline nUpdate.Test/UseDynamicUriTest.cs]: Please rename this to "UseDynamicUpdateUriTest".

File: nUpdate.Test/UseDynamicUriTest.cs [hunk 13]
```diff
@@ -0,0 +1,100 @@
...
+        [TestMethod]
+        public void CanConvertPackageUriWithDomainName()
+        {
+            var literalVersion = "1.0.0.0";
+            var updatePackageUri = new Uri("http://localhost/nNpdate/1.0.0.0/6b56500f-6557-4808-a68f-6c6fb34fb3e4.zip");
+            var updateManager = new UpdateManager(new Uri("http://www.test.de/nNpdate/updates.json"), PUBLIC_KEY, new System.Globalization.CultureInfo("zh-CN"), new UpdateVersion(literalVersion)) { UseDynamicUpdateUri = true };
```
Comment (ProgTrade) [inline nUpdate.Test/UseDynamicUriTest.cs]: Please make some arguments for the update manager instance here more unique (in all test methods).
With that I mean: Set "en" as CultureInfo and please rename "nNpdate" to "nUpdate" or "nupdate" to make it suit better to the project's name.

File: nUpdate.Test/UseDynamicUriTest.cs [hunk 14]
```diff
@@ -0,0 +1,100 @@
...
+            var literalVersion = "1.0.0.0";
+            var statisticsUri = new Uri("http://localhost/nNpdate/statistics.php");
+            var updateManager = new UpdateManager(new Uri("http://www.test.de/nNpdate/updates.json"), PUBLIC_KEY, new System.Globalization.CultureInfo("zh-CN"), new UpdateVersion(literalVersion)) { UseDynamicUpdateUri = true };
+            var targetUri = new Uri("http://www.test.de/nNpdate/statistics.php");
+            PrivateObject privateObject = new PrivateObject(updateManager);
+            Assert.AreEqual(targetUri, privateObject.Invoke("ConvertStatisticsUri", statisticsUri));
+        }
+
+        [TestMethod]
+        public void CanConvertStatisticsUriWithDomainNamePortt()
```
Comment (ProgTrade) [inline nUpdate.Test/UseDynamicUriTest.cs]: Please fix this typo in "Portt".

File: nUpdate.Shared/Updating/UpdateManager.cs [hunk 15]
```diff
@@ -229,6 +229,20 @@ public CultureInfo LanguageCulture
         /// </summary>
         public int SearchTimeout { get; set; } = 10000;
 
+        /// <summary>
+        ///     Gets or sets a value indicating whether the nUpdate set every update package URI (its parent directory) is automatically to the one
```
[the remark this answers is not in the document]
Comment (selway) [reply nUpdate.Shared/Updating/UpdateManager.cs]: I deleted this comment in the modified commit.  I really do not know how to comment it better,  I am afraid I can only trouble you to add a better one.  Please.

File: nUpdate.Shared/Updating/UpdateManager.cs (hunk 7 above)
Comment (selway) [reply nUpdate.Shared/Updating/UpdateManager.cs]: I eventually chose to use `Uri.Segments.Last()` instead of "statistics.php" make it work after "statistics.php" was modified by someone else.

**Comment by selway** [comment]
I changed commit and it now fits almost all suggestions.

File: nUpdate.Test/UseDynamicUriTest.cs (hunk 14 above)
Comment (selway) [reply nUpdate.Test/UseDynamicUriTest.cs]: fixed

File: nUpdate.Test/UseDynamicUriTest.cs (hunk 13 above)
Comment (selway) [reply nUpdate.Test/UseDynamicUriTest.cs]: Changed

File: nUpdate.Test/UseDynamicUriTest.cs (hunk 12 above)
Comment (selway) [reply nUpdate.Test/UseDynamicUriTest.cs]: Renamed

File: nUpdate.Shared/Updating/UpdateManager.cs (hunk 11 above)
Comment (selway) [reply nUpdate.Shared/Updating/UpdateManager.cs]: Removed

File: nUpdate.Shared/Updating/UpdateManager.cs (hunk 10 above)
Comment (selway) [reply nUpdate.Shared/Updating/UpdateManager.cs]: Sorted

File: nUpdate.Shared/Updating/UpdateManager.cs (hunk 3 above)
Comment (selway) [reply nUpdate.Shared/Updating/UpdateManager.cs]: I override this method and now it no longer needs the `literalVersion` parameter.

File: nUpdate.Shared/Updating/UpdateManager.cs (hunk 4 above)
Comment (selway) [reply nUpdate.Shared/Updating/UpdateManager.cs]: Replaced

File: nUpdate.Shared/Updating/UpdateManager.cs (hunk 5 above)
Comment (selway) [reply nUpdate.Shared/Updating/UpdateManager.cs]: I override this method，used the `Uri.GetLeftPart`-method and `Uri.Segments` instead of `Substring`-function.

File: nUpdate.Test/UseDynamicUriTest.cs (hunk 9 above)
Comment (selway) [reply nUpdate.Test/UseDynamicUriTest.cs]: I ran it, and the changed implementation passed the test.

File: nUpdate.Shared/Updating/UpdateManager.cs [hunk 16]
```diff
@@ -273,6 +275,60 @@ private void Cleanup()
             _packageOperations.Clear();
         }
 
+        /// <summary>
```
Comment (ProgTrade) [inline nUpdate.Shared/Updating/UpdateManager.cs]: Please remove the documentation here as this is a private method.

File: nUpdate.Shared/Updating/UpdateManager.cs [hunk 17]
```diff
@@ -273,6 +275,60 @@ private void Cleanup()
...
+            if (updatePackageUri.Segments.Length < 3)
+                throw new ArgumentException($"{ nameof(updatePackageUri)} is not a valid update package URI.", nameof(updatePackageUri));
+            var packageNameSegment = updatePackageUri.Segments.Last();
+            var versionSegment = updatePackageUri.Segments[updatePackageUri.Segments.Length - 2];
+            var baseUri = UpdateConfigurationFileUri.GetLeftPart(UriPartial.Authority);
+            var configLocatedPath = string.Join(string.Empty, UpdateConfigurationFileUri.Segments, 0, UpdateConfigurationFileUri.Segments.Length - 1);
+            return new Uri($"{baseUri}{configLocatedPath}{versionSegment}{packageNameSegment}");
+        }
+
+        /// <summary>
```
Comment (ProgTrade) [inline nUpdate.Shared/Updating/UpdateManager.cs]: Remove the documentation here as well.

File: nUpdate.Shared/Updating/UpdateManager.cs (hunk 16 above)
Comment (selway) [reply nUpdate.Shared/Updating/UpdateManager.cs]: Delete all documents Do not keep any comments?

**Comment by selway** [comment]
I changed the commit, and all unit tests  passed.

**Comment by ProgTrade** [comment]
Thank you very much. Could you only please change the branch to merge into to "develop-v3" instead of "master"? 
Because then I can keep my GitFlow manner and will directly merge it into this branch to prepare for a new release.

**Comment by selway** [comment]
Sorry, I didn’t notice this before, I changed it.
